apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apigw.fullname" . }}
  labels:
    {{- include "apigw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
