{{- if .Values.csv.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "streamer.fullname" . }}-csv
  labels:
    {{- include "streamer.labels" . | nindent 4 }}
data:
  telemetry.csv: |
{{ .Values.csv.data | indent 4 }}
{{- end }}
