apiVersion: v2
name: telemetry-pipeline
description: Umbrella Helm chart â€“ installs all GPU telemetry pipeline components
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
  # ---- Application services ----
  - name: apigw
    version: "0.1.0"
    repository: "file://../apigw"
  - name: mqwriter
    version: "0.1.0"
    repository: "file://../mqwriter"
  - name: mqreader
    version: "0.1.0"
    repository: "file://../mqreader"
  - name: streamer
    version: "0.1.0"
    repository: "file://../streamer"
  - name: collector
    version: "0.1.0"
    repository: "file://../collector"

  # ---- Infrastructure ----
  - name: postgresql
    version: "*"
    repository: "https://charts.bitnami.com/bitnami"
