apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mqreader.fullname" . }}-partitions
  labels:
    {{- include "mqreader.labels" . | nindent 4 }}
data:
  partitions.yaml: |
{{ include "mqreader.partitionData" . | trim | indent 4 }}
