apiVersion: v2
name: prompted
description: Umbrella Helm chart for the prompted Go monorepo
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: apigw
    version: "0.1.0"
    repository: "file://../apigw"
  - name: mqwriter
    version: "0.1.0"
    repository: "file://../mqwriter"
  - name: mqreader
    version: "0.1.0"
    repository: "file://../mqreader"
  - name: streamer
    version: "0.1.0"
    repository: "file://../streamer"
  - name: collector
    version: "0.1.0"
    repository: "file://../collector"
