apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "partition-controller.fullname" . }}
  labels:
    {{- include "partition-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "watch", "list", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "partition-controller.fullname" . }}
  labels:
    {{- include "partition-controller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "partition-controller.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "partition-controller.fullname" . }}
